# Generated by Django 5.0.6 on 2024-05-27 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='license',
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='licence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.licence'),
        ),
    ]
