# Generated by Django 5.0.6 on 2024-05-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_licence_description_alter_licence_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.licence', to_field='name'),
        ),
    ]
