# Generated by Django 5.1 on 2024-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='letter',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
