# Generated by Django 5.0.6 on 2024-06-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_alter_module_name_questiontypea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answerA', models.CharField(max_length=100)),
                ('answerB', models.CharField(max_length=100)),
                ('answerC', models.CharField(max_length=100)),
                ('answerD', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module', to_field='name')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionTypeA',
        ),
    ]
