# Generated by Django 5.0.6 on 2024-06-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_question_delete_questiontypea'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
