# Generated by Django 5.0.6 on 2024-06-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
