# Generated by Django 5.0.6 on 2024-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_student_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curp',
            field=models.CharField(max_length=18),
        ),
    ]
